{*
 * @version $Id: $
 * @author Gaetano Giunta
 * @copyright (c) 2008 G. Giunta
 * @license code licensed under the GPL License: see README
 *
 * DO NOT EDIT THIS FILE! Use an override template instead.
 *}
<node node_id="{$node.node_id}" parent_node_id="{$node.parent_node_id}" depth="{$node.depth}">
  <object id="{$node.contentobject_id}" name="{$node.object.name|washxml}" current_version="{$node.contentobject_version}" main_node_id="{$node.object.main_node_id}">
    <{$node.object.class_name|washxml}>
{foreach $node.object.data_map as $item}
{attribute_view_gui view = xml attribute = $item}
{/foreach}
    </{$node.object.class_name|washxml}>
  </object>
  <children>
{* @todo verify if using $node.children has same sort order, creates same compiled code *}
{let children = fetch( 'content', 'list', hash( parent_node_id, $node.node_id, sort_by, $node.sort_array ) )}
{foreach $children as $item}
{* NB: full recursive view of all child nodes *}
{node_view_gui view = xml content_node = $item}
{/foreach}
  </children>
</node>
